spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

  application:
    segurity:
      jwt:
        secret: mySecretKey
        expiration: 3600000
        refres-token:
        expiration: 7200000
